In [29]:
mport pandas as pd
import numpy as np
import glob
import matplotlib as mat
import matplotlib.pyplot as plt
import seaborn as sns
import xlrd
import platform
import json
import googlemaps
import folium
from matplotlib import font_manager , rc

SyntaxError: invalid syntax (3099741654.py, line 1)

In [26]:
pop_crime = pd.read_excel('서울시_구별_범죄발생_인구수.xlsx', index_col = 0)
pop_crime

시도   시군구  2017 범죄발생합계  2018 범죄발생합계  2019 범죄발생합계  2017 인구합계  2018 인구합계  \
0   서울특별시   강남구         7720         7513         7304     561052     547453   
1   서울특별시   강동구         4261         3919         4014     440359     431920   
2   서울특별시   강북구         3393         3437         3838     328002     322915   
3   서울특별시   강서구         5135         4629         4924     608255     603611   
4   서울특별시   관악구         5525         5026         5328     520929     520040   
5   서울특별시   광진구         4646         3915         4011     372298     371063   
6   서울특별시   구로구         4895         4810         4707     441559     438486   
7   서울특별시   금천구         3265         3293         3105     253491     254021   
8   서울특별시   노원구         4209         4007         4153     558075     548160   
9   서울특별시   도봉구         1999         2249         2110     346234     341649   
10  서울특별시  동대문구         3975         3680         3692     366011     364338   
11  서울특별시   동작구         3330         3100         3400     408493     409385   
12  서울특별시   마포구         5278         5172         4842     385783     386359   
13  서울특별시  서대문구         3113         2802         2943     325028     323080   
14  서울특별시   서초구         4708         4726         5542     445401     438163   
15  서울특별시   성동구         2767         2457         2512     312711     316463   
16  서울특별시   성북구         3434         3042         2877     455407     447687   
17  서울특별시   송파구         5576         5807         5698     671173     673507   
18  서울특별시   양천구         3882         3515         3214     475018     468145   
19  서울특별시  영등포구         5969         5840         5820     402024     403600   
20  서울특별시   용산구         4060         3411         3313     244444     245090   
21  서울특별시   은평구         3883         3590         3880     491202     487666   
22  서울특별시   종로구         4057         3690         3846     164257     163026   
23  서울특별시    중구         4184         4030         4327     134593     135633   
24  서울특별시   중랑구         4571         4288         4268     412780     408147   

    2019 인구합계  2017인구대비  2018인구대비  2019인구대비  
0      550209  1.375987  1.372355  1.327496  
1      440390  0.967620  0.907344  0.911465  
2      317695  1.034445  1.064367  1.208077  
3      598273  0.844218  0.766885  0.823036  
4      517334  1.060605  0.966464  1.029896  
5      366972  1.247925  1.055077  1.092999  
6      439371  1.108572  1.096956  1.071304  
7      251820  1.288014  1.296350  1.233024  
8      537303  0.754200  0.730991  0.772934  
9      335631  0.577355  0.658278  0.628667  
10     363023  1.086033  1.010051  1.017015  
11     408912  0.815191  0.757233  0.831475  
12     385925  1.368127  1.338651  1.254648  
13     323171  0.957764  0.867277  0.910663  
14     435107  1.057025  1.078594  1.273710  
15     308979  0.884843  0.776394  0.813000  
16     454744  0.754051  0.679493  0.632664  
17     682741  0.830784  0.862203  0.834577  
18     462285  0.817232  0.750836  0.695242  
19     400986  1.484737  1.446977  1.451422  
20     245185  1.660912  1.391734  1.351225  
21     484546  0.790510  0.736160  0.800750  
22     161869  2.469910  2.263443  2.375995  
23     136488  3.108631  2.971253  3.170242  
24     402024  1.107370  1.050602  1.061628

In [27]:
sports = pd.read_excel('체육시설_구별_갯수_total.xlsx', index_col = 0)
sports

시도   시군구  2017  2018  2019  2017~2018  2018~2019  2017~2019
0   서울특별시   강남구   225   232   234          7          2          9
1   서울특별시   강동구   130   127   126         -3         -1         -4
2   서울특별시   강북구    80    70    68        -10         -2        -12
3   서울특별시   강서구   159   158   144         -1        -14        -15
4   서울특별시   관악구   157   153   150         -4         -3         -7
5   서울특별시   광진구    68    60    60         -8          0         -8
6   서울특별시   구로구    92    94    92          2         -2          0
7   서울특별시   금천구    55    56    52          1         -4         -3
8   서울특별시   노원구   157   160   160          3          0          3
9   서울특별시   도봉구    94    94    96          0          2          2
10  서울특별시  동대문구    92    89    86         -3         -3         -6
11  서울특별시   동작구    85    83    85         -2          2          0
12  서울특별시   마포구    95    99    96          4         -3          1
13  서울특별시  서대문구    81    80    81         -1          1          0
14  서울특별시   서초구    85    85    87          0          2          2
15  서울특별시   성동구    89    86    79         -3         -7        -10
16  서울특별시   성북구   110   106   112         -4          6          2
17  서울특별시   송파구   189   185   182         -4         -3         -7
18  서울특별시   양천구   150   151   134          1        -17        -16
19  서울특별시  영등포구   112   110   107         -2         -3         -5
20  서울특별시   용산구    49    51    52          2          1          3
21  서울특별시   은평구   116   116   116          0          0          0
22  서울특별시   종로구    42    39    39         -3          0         -3
23  서울특별시    중구     5     6     7          1          1          2
24  서울특별시   중랑구   122   119   115         -3         -4         -7

In [28]:
print(np.corrcoef(pop_crime['2017인구대비'],sports['2017']))
print(np.corrcoef(pop_crime['2018인구대비'],sports['2018']))
print(np.corrcoef(pop_crime['2019인구대비'],sports['2019']))

[[ 1.         -0.55180129]
 [-0.55180129  1.        ]]
[[ 1.         -0.50424098]
 [-0.50424098  1.        ]]
[[ 1.         -0.51928505]
 [-0.51928505  1.        ]]


In [25]:
print(np.corrcoef(pop_crime['2017 범죄발생합계'],sports['2017~2018']))
print(np.corrcoef(pop_crime['2018 범죄발생합계'],sports['2018~2019']))
print(np.corrcoef(pop_crime['2019 범죄발생합계'],sports['2017~2019']))

[[1.         0.30697197]
 [0.30697197 1.        ]]
[[ 1.         -0.04019715]
 [-0.04019715  1.        ]]
[[1.         0.15278446]
 [0.15278446 1.        ]]
