In [10]:
import pandas as pd
import numpy as np
import glob
import matplotlib as mat
import matplotlib.pyplot as plt
import seaborn as sns
import xlrd
import platform
import json
import googlemaps
import folium
from matplotlib import font_manager , rc
f_path = "/Library/Fonts/Arial Unicode.ttf"
font_name = font_manager.FontProperties(fname=f_path).get_name()
rc('font', family=font_name)

In [11]:
pop_crime = pd.read_excel('../data/서울시_구별_범죄발생_인구수.xlsx', index_col = 0)
pop_crime.head()

시도  시군구  2017 범죄발생합계  2018 범죄발생합계  2019 범죄발생합계  2017 인구합계  2018 인구합계  \
0  서울특별시  강남구         7720         7513         7304     561052     547453   
1  서울특별시  강동구         4261         3919         4014     440359     431920   
2  서울특별시  강북구         3393         3437         3838     328002     322915   
3  서울특별시  강서구         5135         4629         4924     608255     603611   
4  서울특별시  관악구         5525         5026         5328     520929     520040   

   2019 인구합계  
0     550209  
1     440390  
2     317695  
3     598273  
4     517334

In [12]:
lib = pd.read_excel('../data/극장_통합_구별_개수_total.xlsx', index_col = 0)
lib.head()

시도  시군구  2017  2018  2019  2017~2018  2018~2019  2017~2019
0  서울특별시  강남구    48    54    56          6          2          8
1  서울특별시  강동구    16    16    16          0          0          0
2  서울특별시  강북구     5     6     6          1          0          1
3  서울특별시  강서구     6     5     6         -1          1          0
4  서울특별시  관악구     2     2     2          0          0          0

In [13]:
theater = pd.read_excel('../data/극장_통합_구별_개수_total.xlsx', index_col = 0)
theater.head()

시도  시군구  2017  2018  2019  2017~2018  2018~2019  2017~2019
0  서울특별시  강남구    48    54    56          6          2          8
1  서울특별시  강동구    16    16    16          0          0          0
2  서울특별시  강북구     5     6     6          1          0          1
3  서울특별시  강서구     6     5     6         -1          1          0
4  서울특별시  관악구     2     2     2          0          0          0

In [14]:
print(np.corrcoef(pop_crime['2017 범죄발생합계'],lib['2017']))
print(np.corrcoef(pop_crime['2018 범죄발생합계'],lib['2018']))
print(np.corrcoef(pop_crime['2019 범죄발생합계'],lib['2019']))

[[ 1.         -0.01602333]
 [-0.01602333  1.        ]]
[[ 1.         -0.00951075]
 [-0.00951075  1.        ]]
[[1.         0.05609069]
 [0.05609069 1.        ]]


In [15]:
print(np.corrcoef(pop_crime['2017 범죄발생합계'],lib['2017~2018']))
print(np.corrcoef(pop_crime['2018 범죄발생합계'],lib['2018~2019']))
print(np.corrcoef(pop_crime['2019 범죄발생합계'],lib['2017~2019']))

[[1.         0.19525064]
 [0.19525064 1.        ]]
[[1.         0.06640707]
 [0.06640707 1.        ]]
[[1.         0.12870705]
 [0.12870705 1.        ]]


In [16]:
print(np.corrcoef(pop_crime['2017 범죄발생합계'],lib['2017']))
print(np.corrcoef(pop_crime['2018 범죄발생합계'],lib['2018']))
print(np.corrcoef(pop_crime['2019 범죄발생합계'],lib['2019']))

[[ 1.         -0.01602333]
 [-0.01602333  1.        ]]
[[ 1.         -0.00951075]
 [-0.00951075  1.        ]]
[[1.         0.05609069]
 [0.05609069 1.        ]]


In [17]:
print(np.corrcoef(pop_crime['2017 범죄발생합계'],theater['2017']))
print(np.corrcoef(pop_crime['2018 범죄발생합계'],theater['2018']))
print(np.corrcoef(pop_crime['2019 범죄발생합계'],theater['2019']))

[[ 1.         -0.01602333]
 [-0.01602333  1.        ]]
[[ 1.         -0.00951075]
 [-0.00951075  1.        ]]
[[1.         0.05609069]
 [0.05609069 1.        ]]


In [18]:
print(np.corrcoef(pop_crime['2017 범죄발생합계'],theater['2017~2018']))
print(np.corrcoef(pop_crime['2018 범죄발생합계'],theater['2018~2019']))
print(np.corrcoef(pop_crime['2019 범죄발생합계'],theater['2017~2019']))

[[1.         0.19525064]
 [0.19525064 1.        ]]
[[1.         0.06640707]
 [0.06640707 1.        ]]
[[1.         0.12870705]
 [0.12870705 1.        ]]
