In [2]:
import pandas as pd
import numpy as np

In [3]:
control_crime = pd.read_excel('//Users/hajihyuk/Documents/1차 미니 프로젝트/상관분석/범죄억제시설_상관분석.xlsx', index_col=0)
control_crime.head()

시군구  2017범죄억제시설합계  2018범죄억제시설합계  2019범죄억제시설합계  2017범죄발생률  2018범죄발생률  \
0  강남구           346           369           374   1.375987   1.372355   
1  강동구           182           183           182   0.967620   0.907344   
2  강북구           106            99            97   1.034445   1.064367   
3  강서구           201           201           191   0.844218   0.766885   
4  관악구           178           175           174   1.060605   0.966464   

   2019범죄발생률  
0   1.327496  
1   0.911465  
2   1.208077  
3   0.823036  
4   1.029896

In [4]:
control_crime

시군구  2017범죄억제시설합계  2018범죄억제시설합계  2019범죄억제시설합계  2017범죄발생률  2018범죄발생률  \
0    강남구           346           369           374   1.375987   1.372355   
1    강동구           182           183           182   0.967620   0.907344   
2    강북구           106            99            97   1.034445   1.064367   
3    강서구           201           201           191   0.844218   0.766885   
4    관악구           178           175           174   1.060605   0.966464   
5    광진구           100            93            94   1.247925   1.055077   
6    구로구           129           135           137   1.108572   1.096956   
7    금천구            79            80            78   1.288014   1.296350   
8    노원구           192           199           200   0.754200   0.730991   
9    도봉구           124           126           128   0.577355   0.658278   
10  동대문구           134           131           131   1.086033   1.010051   
11   동작구           188           188           190   0.815191   0.757233   
12   마포구           139           144           145   1.368127   1.338651   
13  서대문구           109           114           115   0.957764   0.867277   
14   서초구           142           146           152   1.057025   1.078594   
15   성동구           114           112           108   0.884843   0.776394   
16   성북구           142           141           150   0.754051   0.679493   
17   송파구           242           239           243   0.830784   0.862203   
18   양천구           178           184           169   0.817232   0.750836   
19  영등포구           165           168           165   1.484737   1.446977   
20   용산구            70            73            78   1.660912   1.391734   
21   은평구           338           340           342   0.790510   0.736160   
22   종로구           157           166           174   2.469910   2.263443   
23    중구           239           240           242   3.108631   2.971253   
24   중랑구           146           145           142   1.107370   1.050602   

    2019범죄발생률  
0    1.327496  
1    0.911465  
2    1.208077  
3    0.823036  
4    1.029896  
5    1.092999  
6    1.071304  
7    1.233024  
8    0.772934  
9    0.628667  
10   1.017015  
11   0.831475  
12   1.254648  
13   0.910663  
14   1.273710  
15   0.813000  
16   0.632664  
17   0.834577  
18   0.695242  
19   1.451422  
20   1.351225  
21   0.800750  
22   2.375995  
23   3.170242  
24   1.061628

In [5]:
np.corrcoef(control_crime['2017범죄발생률'],control_crime['2017범죄억제시설합계'])

array([[1.        , 0.05210448],
       [0.05210448, 1.        ]])

In [8]:
np.corrcoef(control_crime['2018범죄발생률'],control_crime['2018범죄억제시설합계'])

array([[1.        , 0.10053074],
       [0.10053074, 1.        ]])

In [9]:
np.corrcoef(control_crime['2019범죄발생률'],control_crime['2019범죄억제시설합계'])

array([[1.        , 0.12480521],
       [0.12480521, 1.        ]])

In [14]:
print(control_crime['2017범죄억제시설합계'].sum())
print(control_crime['2018범죄억제시설합계'].sum())
print(control_crime['2019범죄억제시설합계'].sum())

4140
4191
4201


In [16]:
entice_crime = pd.read_excel('/Users/hajihyuk/Documents/1차 미니 프로젝트/상관분석/범죄유인시설_상관분석.xlsx', index_col=0)
entice_crime.head()

시군구  2017범죄유인시설합계  2018범죄유인시설합계  2019범죄유인시설합계  2017범죄발생률  2018범죄발생률  \
0  강남구          1013          1017          1010   1.375987   1.372355   
1  강동구           533           538           530   0.967620   0.907344   
2  강북구           691           710           699   1.034445   1.064367   
3  강서구           915           922           904   0.844218   0.766885   
4  관악구           624           618           608   1.060605   0.966464   

   2019범죄발생률  
0   1.327496  
1   0.911465  
2   1.208077  
3   0.823036  
4   1.029896

In [ ]:
entice_crime

In [17]:
np.corrcoef(entice_crime['2017범죄발생률'],entice_crime['2017범죄유인시설합계'])

array([[1.        , 0.30199811],
       [0.30199811, 1.        ]])

In [18]:
np.corrcoef(entice_crime['2018범죄발생률'],entice_crime['2018범죄유인시설합계'])

array([[1.       , 0.3362033],
       [0.3362033, 1.       ]])

In [19]:
np.corrcoef(entice_crime['2019범죄발생률'],entice_crime['2019범죄유인시설합계'])

array([[1.       , 0.3556426],
       [0.3556426, 1.       ]])

In [21]:
entice_cri = pd.read_excel('/Users/hajihyuk/Documents/1차 미니 프로젝트/상관분석/범죄유인시설합계(pc제외)_상관분석.xlsx', index_col=0)
entice_cri.head()

시군구  2017범죄유인시설합계  2018범죄유인시설합계  2019범죄유인시설합계  2017범죄발생률  2018범죄발생률  \
0  강남구           586           575           568   1.375987   1.372355   
1  강동구           335           317           309   0.967620   0.907344   
2  강북구           334           328           317   1.034445   1.064367   
3  강서구           454           444           426   0.844218   0.766885   
4  관악구           461           440           430   1.060605   0.966464   

   2019범죄발생률  
0   1.327496  
1   0.911465  
2   1.208077  
3   0.823036  
4   1.029896

In [22]:
np.corrcoef(entice_cri['2017범죄발생률'],entice_cri['2017범죄유인시설합계'])

array([[1.        , 0.65649549],
       [0.65649549, 1.        ]])

In [23]:
np.corrcoef(entice_cri['2018범죄발생률'],entice_cri['2018범죄유인시설합계'])

array([[1.        , 0.69363611],
       [0.69363611, 1.        ]])

In [24]:
np.corrcoef(entice_cri['2019범죄발생률'],entice_cri['2019범죄유인시설합계'])

array([[1.        , 0.71419944],
       [0.71419944, 1.        ]])

# pc방 포함과 포함하지 않은 상관관계를 근거로 pc방을 유인시설에서 제외한 근거

In [26]:
print(entice_cri['2017범죄유인시설합계'].sum())
print(entice_cri['2018범죄유인시설합계'].sum())
print(entice_cri['2019범죄유인시설합계'].sum())

7278
7128
6978
