In [1]:
import pandas as pd
import numpy as np

In [2]:
motel = pd.read_excel('/Users/hajihyuk/Documents/숙박업.xlsx')

In [3]:
adult = pd.read_excel('/Users/hajihyuk/Documents/유흥주점.xlsx')

In [4]:
people_crime = pd.read_excel('/Users/hajihyuk/Documents/서울시_구별_범죄발생_인구수.xlsx')

In [5]:
motel.head()

시군구  2017숙박업소합계  2018숙박업소합계  2019숙박업소합계
0  강남구         157         156         153
1  강동구         113         105          97
2  강북구         182         176         169
3  강서구         174         159         143
4  관악구         171         158         148

In [6]:
adult.head()

시군구  2017유흥주점합계  2018유흥주점합계  2019유흥주점합계
0  강남구         233         222         218
1  강동구         143         133         131
2  강북구          73          73          69
3  강서구         133         133         130
4  관악구         220         212         211

In [7]:
people_crime.head()

Unnamed: 0     시도  시군구  2017 범죄발생합계  2018 범죄발생합계  2019 범죄발생합계  2017 인구합계  \
0           0  서울특별시  강남구         7720         7513         7304     561052   
1           1  서울특별시  강동구         4261         3919         4014     440359   
2           2  서울특별시  강북구         3393         3437         3838     328002   
3           3  서울특별시  강서구         5135         4629         4924     608255   
4           4  서울특별시  관악구         5525         5026         5328     520929   

   2018 인구합계  2019 인구합계  
0     547453     550209  
1     431920     440390  
2     322915     317695  
3     603611     598273  
4     520040     517334

In [8]:
p_crime = people_crime.drop(['Unnamed: 0'], axis=1)
p_crime.head()

시도  시군구  2017 범죄발생합계  2018 범죄발생합계  2019 범죄발생합계  2017 인구합계  2018 인구합계  \
0  서울특별시  강남구         7720         7513         7304     561052     547453   
1  서울특별시  강동구         4261         3919         4014     440359     431920   
2  서울특별시  강북구         3393         3437         3838     328002     322915   
3  서울특별시  강서구         5135         4629         4924     608255     603611   
4  서울특별시  관악구         5525         5026         5328     520929     520040   

   2019 인구합계  
0     550209  
1     440390  
2     317695  
3     598273  
4     517334

In [11]:
p_crime['2017범죄발생률'] = p_crime['2017 범죄발생합계'] / p_crime['2017 인구합계']*100
p_crime['2018범죄발생률'] = p_crime['2018 범죄발생합계'] / p_crime['2018 인구합계']*100
p_crime['2019범죄발생률'] = p_crime['2019 범죄발생합계'] / p_crime['2019 인구합계']*100
p_crime.head()

시도  시군구  2017 범죄발생합계  2018 범죄발생합계  2019 범죄발생합계  2017 인구합계  2018 인구합계  \
0  서울특별시  강남구         7720         7513         7304     561052     547453   
1  서울특별시  강동구         4261         3919         4014     440359     431920   
2  서울특별시  강북구         3393         3437         3838     328002     322915   
3  서울특별시  강서구         5135         4629         4924     608255     603611   
4  서울특별시  관악구         5525         5026         5328     520929     520040   

   2019 인구합계  2017범죄발생률  2018범죄발생률  2019범죄발생률  
0     550209   1.375987   1.372355   1.327496  
1     440390   0.967620   0.907344   0.911465  
2     317695   1.034445   1.064367   1.208077  
3     598273   0.844218   0.766885   0.823036  
4     517334   1.060605   0.966464   1.029896

In [15]:
crime = p_crime[['시도', '시군구', '2017범죄발생률', '2018범죄발생률', '2019범죄발생률']]
crime

시도   시군구  2017범죄발생률  2018범죄발생률  2019범죄발생률
0   서울특별시   강남구   1.375987   1.372355   1.327496
1   서울특별시   강동구   0.967620   0.907344   0.911465
2   서울특별시   강북구   1.034445   1.064367   1.208077
3   서울특별시   강서구   0.844218   0.766885   0.823036
4   서울특별시   관악구   1.060605   0.966464   1.029896
5   서울특별시   광진구   1.247925   1.055077   1.092999
6   서울특별시   구로구   1.108572   1.096956   1.071304
7   서울특별시   금천구   1.288014   1.296350   1.233024
8   서울특별시   노원구   0.754200   0.730991   0.772934
9   서울특별시   도봉구   0.577355   0.658278   0.628667
10  서울특별시  동대문구   1.086033   1.010051   1.017015
11  서울특별시   동작구   0.815191   0.757233   0.831475
12  서울특별시   마포구   1.368127   1.338651   1.254648
13  서울특별시  서대문구   0.957764   0.867277   0.910663
14  서울특별시   서초구   1.057025   1.078594   1.273710
15  서울특별시   성동구   0.884843   0.776394   0.813000
16  서울특별시   성북구   0.754051   0.679493   0.632664
17  서울특별시   송파구   0.830784   0.862203   0.834577
18  서울특별시   양천구   0.817232   0.750836   0.695242
19  서울특별시  영등포구   1.484737   1.446977   1.451422
20  서울특별시   용산구   1.660912   1.391734   1.351225
21  서울특별시   은평구   0.790510   0.736160   0.800750
22  서울특별시   종로구   2.469910   2.263443   2.375995
23  서울특별시    중구   3.108631   2.971253   3.170242
24  서울특별시   중랑구   1.107370   1.050602   1.061628

In [16]:
motel_cor = pd.merge(crime, motel, on='시군구')
motel_cor.head()

시도  시군구  2017범죄발생률  2018범죄발생률  2019범죄발생률  2017숙박업소합계  2018숙박업소합계  \
0  서울특별시  강남구   1.375987   1.372355   1.327496         157         156   
1  서울특별시  강동구   0.967620   0.907344   0.911465         113         105   
2  서울특별시  강북구   1.034445   1.064367   1.208077         182         176   
3  서울특별시  강서구   0.844218   0.766885   0.823036         174         159   
4  서울특별시  관악구   1.060605   0.966464   1.029896         171         158   

   2019숙박업소합계  
0         153  
1          97  
2         169  
3         143  
4         148

In [18]:
np.corrcoef(motel_cor['2017범죄발생률'],motel_cor['2017숙박업소합계'])

array([[1.        , 0.76407234],
       [0.76407234, 1.        ]])

In [19]:
np.corrcoef(motel_cor['2018범죄발생률'],motel_cor['2018숙박업소합계'])

array([[1.        , 0.80882597],
       [0.80882597, 1.        ]])

In [20]:
np.corrcoef(motel_cor['2019범죄발생률'],motel_cor['2019숙박업소합계'])

array([[1.       , 0.8516362],
       [0.8516362, 1.       ]])

In [17]:
adult_cor = pd.merge(crime, adult, on='시군구')
adult_cor.head()

시도  시군구  2017범죄발생률  2018범죄발생률  2019범죄발생률  2017유흥주점합계  2018유흥주점합계  \
0  서울특별시  강남구   1.375987   1.372355   1.327496         233         222   
1  서울특별시  강동구   0.967620   0.907344   0.911465         143         133   
2  서울특별시  강북구   1.034445   1.064367   1.208077          73          73   
3  서울특별시  강서구   0.844218   0.766885   0.823036         133         133   
4  서울특별시  관악구   1.060605   0.966464   1.029896         220         212   

   2019유흥주점합계  
0         218  
1         131  
2          69  
3         130  
4         211

In [24]:
np.corrcoef(adult_cor['2017범죄발생률'],adult_cor['2017유흥주점합계'])

array([[1.        , 0.60316446],
       [0.60316446, 1.        ]])

In [25]:
np.corrcoef(adult_cor['2018범죄발생률'],adult_cor['2018유흥주점합계'])

array([[1.        , 0.62692589],
       [0.62692589, 1.        ]])

In [26]:
np.corrcoef(adult_cor['2019범죄발생률'],adult_cor['2019유흥주점합계'])

array([[1.        , 0.62860086],
       [0.62860086, 1.        ]])